// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['entity'], function(Entity) {
    var Creature;
    Creature = (function(_super) {

      __extends(Creature, _super);

      function Creature() {
        return Creature.__super__.constructor.apply(this, arguments);
      }

      Creature.prototype.move_scene = function() {};

      Creature.prototype.remove = function() {
        return creatures.splice(creatures.indexOf(this), 1);
      };

      Creature.prototype.add = function() {
        return creatures.push(this);
      };

      Creature.prototype.set_stats = function() {
        this.health = 5;
        return this.attack = 1;
      };

      return Creature;

    })(Entity);
    return Creature;
  });

}).call(this);
