// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['entity'], function(Entity) {
    var Creature;
    return Creature = (function(_super) {

      __extends(Creature, _super);

      function Creature() {
        return Creature.__super__.constructor.apply(this, arguments);
      }

      Creature.prototype.move_scene = function() {};

      Creature.prototype.set_stats = function() {
        this.health = 5;
        return this.attack = 1;
      };

      Creature.prototype.create_images = function() {
        return this.images = {
          up: {
            x: 1,
            y: 4
          },
          left: {
            x: 3,
            y: 4
          },
          down: {
            x: 2,
            y: 4
          },
          right: {
            x: 4,
            y: 4
          }
        };
      };

      return Creature;

    })(Entity);
  });

}).call(this);
