// Generated by CoffeeScript 1.3.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(['underscore', 'perlin'], function(_, PerlinNoise) {
    var Game;
    Game = (function() {

      function Game() {
        var x, y;
        this.ui_height = 30;
        this.width = 30;
        this.height = 20;
        this.tile_size = 30;
        this.screen_width = this.width * this.tile_size;
        this.screen_height = this.height * this.tile_size + this.ui_height;
        this.world_width = this.width * 2;
        this.world_height = this.height * 2;
        this.num_creatures = 10;
        this.num_trees = 100;
        this.perlin_size = 5;
        this.perlin_z_axis = .8;
        this.ctx = null;
        this.solid_tiles = [2, 3];
        this.solid_objects = [1];
        this.empty_tiles = [];
        this.objects = (function() {
          var _i, _ref, _results;
          _results = [];
          for (y = _i = 1, _ref = this.world_height; 1 <= _ref ? _i <= _ref : _i >= _ref; y = 1 <= _ref ? ++_i : --_i) {
            _results.push((function() {
              var _j, _ref1, _results1;
              _results1 = [];
              for (x = _j = 1, _ref1 = this.world_width; 1 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 1 <= _ref1 ? ++_j : --_j) {
                _results1.push(0);
              }
              return _results1;
            }).call(this));
          }
          return _results;
        }).call(this);
        this.world = (function() {
          var _i, _ref, _results;
          _results = [];
          for (y = _i = 1, _ref = this.world_height; 1 <= _ref ? _i <= _ref : _i >= _ref; y = 1 <= _ref ? ++_i : --_i) {
            _results.push((function() {
              var _j, _ref1, _results1;
              _results1 = [];
              for (x = _j = 1, _ref1 = this.world_width; 1 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 1 <= _ref1 ? ++_j : --_j) {
                _results1.push(3);
              }
              return _results1;
            }).call(this));
          }
          return _results;
        }).call(this);
        this.generate_world();
        this.add_trees();
      }

      Game.prototype.draw_texture = function(sx, sy, dx, dy) {
        var ts;
        ts = this.tile_size;
        return this.ctx.drawImage(texture_canvas, sx * ts, sy * ts, ts, ts, dx * ts, dy * ts, ts, ts);
      };

      Game.prototype.add_trees = function() {
        var i, index, potential_trees, tree, trees, _i, _j, _len, _ref, _results;
        potential_trees = _.clone(this.empty_tiles);
        trees = [];
        for (i = _i = 1, _ref = this.num_trees; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
          index = Math.floor(Math.random() * potential_trees.length);
          trees.push(potential_trees.splice(index, 1)[0]);
        }
        _results = [];
        for (_j = 0, _len = trees.length; _j < _len; _j++) {
          tree = trees[_j];
          _results.push(this.objects[tree.y][tree.x] = 1);
        }
        return _results;
      };

      Game.prototype.generate_world = function() {
        var tile, x, y, _i, _ref, _results;
        _results = [];
        for (y = _i = 1, _ref = this.world_height - 2; 1 <= _ref ? _i <= _ref : _i >= _ref; y = 1 <= _ref ? ++_i : --_i) {
          _results.push((function() {
            var _j, _ref1, _results1;
            _results1 = [];
            for (x = _j = 1, _ref1 = this.world_width - 2; 1 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 1 <= _ref1 ? ++_j : --_j) {
              tile = this.block_type(PerlinNoise(this.perlin_size * x / this.world_width, this.perlin_size * y / this.world_height, this.perlin_z_axis));
              this.world[y][x] = tile;
              if (__indexOf.call(this.solid_tiles, tile) < 0) {
                _results1.push(this.empty_tiles.push({
                  x: x,
                  y: y
                }));
              } else {
                _results1.push(void 0);
              }
            }
            return _results1;
          }).call(this));
        }
        return _results;
      };

      Game.prototype.block_type = function(height) {
        if (height <= .3) {
          return 2;
        }
        if ((.3 < height && height <= .4)) {
          return 4;
        }
        if ((.4 < height && height <= .7)) {
          return 1;
        }
        return 3;
      };

      return Game;

    })();
    return new Game;
  });

}).call(this);
