// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['npc'], function(NPC) {
    var Lumberjack;
    return Lumberjack = (function(_super) {

      __extends(Lumberjack, _super);

      function Lumberjack() {
        return Lumberjack.__super__.constructor.apply(this, arguments);
      }

      Lumberjack.prototype.move_scene = function() {};

      Lumberjack.prototype.create_images = function() {
        return this.images = {
          up: {
            x: 9,
            y: 2
          },
          left: {
            x: 11,
            y: 2
          },
          down: {
            x: 10,
            y: 2
          },
          right: {
            x: 12,
            y: 2
          }
        };
      };

      Lumberjack.prototype.set_stats = function() {
        this.name = 'Lumberjack';
        this.phrases = ["Choppin' logs is a good way to make a livin'.", "How d'you like our little town?"];
        this.phrase_index = 0;
        this.selling = false;
        return this.item_id = 5;
      };

      return Lumberjack;

    })(NPC);
  });

}).call(this);
