// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(['underscore', 'entity', 'game', 'scene'], function(_, Entity, g, s) {
    var Fish, Item, Log, Player, Rock;
    Item = (function() {

      function Item() {
        this.set_id();
      }

      return Item;

    })();
    Log = (function(_super) {

      __extends(Log, _super);

      function Log() {
        return Log.__super__.constructor.apply(this, arguments);
      }

      Log.prototype.set_id = function() {
        return this.id = 5;
      };

      return Log;

    })(Item);
    Fish = (function(_super) {

      __extends(Fish, _super);

      function Fish() {
        return Fish.__super__.constructor.apply(this, arguments);
      }

      Fish.prototype.set_id = function() {
        return this.id = 2;
      };

      return Fish;

    })(Item);
    Rock = (function(_super) {

      __extends(Rock, _super);

      function Rock() {
        return Rock.__super__.constructor.apply(this, arguments);
      }

      Rock.prototype.set_id = function() {
        return this.id = 3;
      };

      return Rock;

    })(Item);
    Player = (function(_super) {

      __extends(Player, _super);

      function Player() {
        return Player.__super__.constructor.apply(this, arguments);
      }

      Player.prototype.move_scene = function() {
        var item, new_scene, _i, _len, _ref;
        new_scene = false;
        _ref = [
          {
            axis: 'x',
            dimension: g.width
          }, {
            axis: 'y',
            dimension: g.height
          }
        ];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          if (this.pos[item.axis] === 0 && this.axis === item.axis && this.direction === -1) {
            this.pos[item.axis] = item.dimension;
            s.pos[item.axis] -= 1;
            new_scene = true;
          }
          if (this.pos[item.axis] === item.dimension - 1 && this.axis === item.axis && this.direction === 1) {
            this.pos[item.axis] = -1;
            s.pos[item.axis] += 1;
            new_scene = true;
          }
        }
        if (new_scene) {
          return s.set();
        }
      };

      Player.prototype.create_images = function() {
        return this.images = {
          up: {
            x: 1,
            y: 2
          },
          left: {
            x: 3,
            y: 2
          },
          down: {
            x: 2,
            y: 2
          },
          right: {
            x: 4,
            y: 2
          }
        };
      };

      Player.prototype.set_stats = function() {
        this.max_health = 10;
        this.health = this.max_health - 5;
        this.attack = 2;
        return this.coins = 0;
      };

      Player.prototype.interact = function() {
        var already_present, creature, free_slots, object, slot, tile, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;
        for (_i = 0, _len = creatures.length; _i < _len; _i++) {
          creature = creatures[_i];
          if (this.in_front.x === creature.pos.x && this.in_front.y === creature.pos.y) {
            creature.health -= this.attack;
            if (creature.health <= 0) {
              creature.remove();
            }
            return;
          }
        }
        tile = this.next_tile;
        object = this.next_object;
        if (__indexOf.call(g.resource_ids, object) >= 0) {
          tile = object;
        }
        if (__indexOf.call(g.resource_ids, tile) < 0) {
          return;
        }
        already_present = false;
        _ref = this.inventory;
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          slot = _ref[_j];
          if (slot.item.id === tile) {
            already_present = true;
            slot.count += 1;
            break;
          }
        }
        if (!already_present) {
          free_slots = false;
          _ref1 = this.inventory;
          for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
            slot = _ref1[_k];
            if (slot.count === 0) {
              slot.count = 1;
              free_slots = true;
              switch (tile) {
                case 5:
                  slot.item = new Log;
                  break;
                case 2:
                  slot.item = new Fish;
                  break;
                case 3:
                  slot.item = new Rock;
              }
              break;
            }
          }
          if (!free_slots) {
            return log('inventory full');
          }
        }
      };

      return Player;

    })(Entity);
    return new Player;
  });

}).call(this);
