// Generated by CoffeeScript 1.3.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(['game'], function(g) {
    var Scene, Scenes;
    Scene = (function() {

      function Scene(x, y) {
        this.x = x;
        this.y = y;
        this.tiles = [];
        this.empty_tiles = [];
        this.objects = [];
        this.load();
        this.num_creatures = 10;
      }

      Scene.prototype.matrix_sub_area = function(matrix, left, top, right, bottom) {
        var row, _i, _len, _ref, _results;
        _ref = matrix.slice(top, (bottom - 1) + 1 || 9e9);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          row = _ref[_i];
          _results.push(row.slice(left, (right - 1) + 1 || 9e9));
        }
        return _results;
      };

      Scene.prototype.load = function() {
        var bottom, cell, left, right, row, top, x, y, _i, _len, _ref, _results;
        left = this.x * g.width;
        top = this.y * g.height;
        right = (this.x + 1) * g.width;
        bottom = (this.y + 1) * g.height;
        if (left === 0) {
          right += g.border;
        } else {
          left -= g.border * this.x;
        }
        if (top === 0) {
          bottom += g.border;
        } else {
          top -= g.border * this.y;
        }
        this.tiles = this.matrix_sub_area(g.world, left, top, right, bottom);
        this.objects = this.matrix_sub_area(g.objects, left, top, right, bottom);
        _ref = this.tiles;
        _results = [];
        for (y = _i = 0, _len = _ref.length; _i < _len; y = ++_i) {
          row = _ref[y];
          _results.push((function() {
            var _j, _len1, _results1;
            _results1 = [];
            for (x = _j = 0, _len1 = row.length; _j < _len1; x = ++_j) {
              cell = row[x];
              if (__indexOf.call(g.solid_things, cell) < 0) {
                _results1.push(this.empty_tiles.push({
                  x: x,
                  y: y
                }));
              } else {
                _results1.push(void 0);
              }
            }
            return _results1;
          }).call(this));
        }
        return _results;
      };

      return Scene;

    })();
    Scenes = (function() {

      function Scenes() {
        var x, y, _i, _j, _ref, _ref1;
        this.num = 2;
        this.pos = {
          x: 0,
          y: 0
        };
        this.scenes = [];
        for (x = _i = 0, _ref = this.num - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
          this.scenes[x] = [];
          for (y = _j = 0, _ref1 = this.num - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
            this.scenes[x][y] = new Scene(x, y);
          }
        }
        this.set();
      }

      Scenes.prototype.set = function() {
        return this.current = this.scenes[this.pos.x][this.pos.y];
      };

      Scenes.prototype.add_creatures = function(Creature) {
        var i, row, scene, x, y, _i, _len, _ref, _results;
        _ref = this.scenes;
        _results = [];
        for (x = _i = 0, _len = _ref.length; _i < _len; x = ++_i) {
          row = _ref[x];
          _results.push((function() {
            var _j, _len1, _results1;
            _results1 = [];
            for (y = _j = 0, _len1 = row.length; _j < _len1; y = ++_j) {
              scene = row[y];
              _results1.push(scene.creatures = (function() {
                var _k, _ref1, _results2;
                _results2 = [];
                for (i = _k = 1, _ref1 = scene.num_creatures; 1 <= _ref1 ? _k <= _ref1 : _k >= _ref1; i = 1 <= _ref1 ? ++_k : --_k) {
                  _results2.push(new Creature(null, {
                    x: x,
                    y: y
                  }));
                }
                return _results2;
              })());
            }
            return _results1;
          })());
        }
        return _results;
      };

      return Scenes;

    })();
    return new Scenes;
  });

}).call(this);
