// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['entity'], function(Entity) {
    var Wizard;
    Wizard = (function(_super) {

      __extends(Wizard, _super);

      function Wizard() {
        return Wizard.__super__.constructor.apply(this, arguments);
      }

      Wizard.prototype.move_scene = function() {};

      Wizard.prototype.create_images = function() {
        return this.images = {
          up: {
            x: 1,
            y: 2
          },
          left: {
            x: 3,
            y: 2
          },
          down: {
            x: 2,
            y: 2
          },
          right: {
            x: 4,
            y: 2
          }
        };
      };

      Wizard.prototype.set_stats = function() {
        this.name = 'Wizard';
        this.phrases = ['Hello', 'Welcome to Comrade', 'If you want to earn some money, try gathering some resources', "I'll buy logs, fish and rocks", 'You can use this money to buy better tools', 'You can also buy weapons and armour to fight the spiders', "Here's a Basic Pickaxe to get you started. Try mining some rocks."];
        return this.phrase_index = 0;
      };

      Wizard.prototype.say = function() {
        var $dialogue, phrase;
        $dialogue = $('#dialogue');
        phrase = this.phrases[this.phrase_index];
        $dialogue.append($('<p>').text("" + this.name + ": " + phrase));
        $dialogue.scrollTop($dialogue[0].scrollHeight);
        this.phrase_index += 1;
        if (this.phrase_index === this.phrases.length) {
          return this.phrase_index = 0;
        }
      };

      return Wizard;

    })(Entity);
    return new Wizard;
  });

}).call(this);
