// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['entity'], function(Entity) {
    var Wizard;
    Wizard = (function(_super) {

      __extends(Wizard, _super);

      function Wizard() {
        return Wizard.__super__.constructor.apply(this, arguments);
      }

      Wizard.prototype.move_scene = function() {};

      Wizard.prototype.create_images = function() {
        return this.images = {
          up: {
            x: 1,
            y: 2
          },
          left: {
            x: 3,
            y: 2
          },
          down: {
            x: 2,
            y: 2
          },
          right: {
            x: 4,
            y: 2
          }
        };
      };

      Wizard.prototype.set_stats = function() {};

      return Wizard;

    })(Entity);
    return new Wizard({
      x: 10,
      y: 10
    });
  });

}).call(this);
